plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\MY PC\\Downloads\\SHREYAS V-PORTFOLIO"
publishOrigin = "config"
base = "C:\\Users\\MY PC\\Downloads\\SHREYAS V-PORTFOLIO"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]